// Instantiations for K=F16, V=TQ_V_4B fattn-vec kernels.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_F16, GGML_TYPE_TQ_V_4B);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_F16, GGML_TYPE_TQ_V_4B);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_F16, GGML_TYPE_TQ_V_4B);
